version: '3.8'

services:
  api:
    build:
      context: .
      target: build
    container_name: backend-api
    # 1. USUNIĘTE PORTY: Ruch z zewnątrz dla api.cinesoft.pl będzie szedł przez Traefika.
    # ports:
    #   - "8080:8080"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ConnectionStrings__DefaultConnection=Server=db;Database=postgresdb;User Id=postgres;Password=postgrespass
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
    depends_on:
      - db
    volumes:
      - .:/src
      - /src/obj
      - /src/bin
    command: >
      bash -c "dotnet dev-certs https --trust;
               dotnet watch run --project /src/MovieReservationSystem.csproj --urls http://*:8080"
    labels:
      # 2. ETYKIETY TRAEFIKA: Automatyczny routing i darmowy certyfikat SSL dla subdomeny API
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.cinesoft.pl`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      # Wskazujemy port, na którym aplikacja .NET nasłuchuje wewnątrz kontenera
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
    networks:
      # 3. SIECI: Podpinamy do globalnej sieci Traefika, aby odbierać ruch,
      # oraz do Twojej lokalnej sieci, by .NET widział bazę PostgreSQL (db).
      - traefik-public
      - app-network

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=postgresdb
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./baza_filmy.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5438:5432" # Zostawiam, abyś mógł łączyć się z bazą bezpośrednio z komputera
    networks:
      - app-network
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-web
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@domena.pl
      - PGADMIN_DEFAULT_PASSWORD=supersecretpass
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/servers.json
    ports:
      - "5050:80" # Zostawiam dostęp do panelu pgAdmin po IP:5050
    volumes:
      - ./servers.json:/pgadmin4/servers.json:ro
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  # Definiujemy sieć zewnętrzną Traefika
  traefik-public:
    external: true
  # Twoja dotychczasowa sieć (movie-system-network) zostaje bez zmian,
  # dzięki czemu api, db i pgadmin idealnie się ze sobą widzą.
  app-network:
    name: movie-system-network
    driver: bridge